[project]
name = "morteiro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "William Leal", email = "wsleeal@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
morteiro = "morteiro:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
